### ISSUE TITLE
AssertionError running test_yahoofinancials.py (line 93)

### ISSUE THREAD

**Issue by crendon8** [JECSand/yahoofinancials#11]
test_historical_price line failed the assertDictEqual(single_stock_prices['C']['prices'][0], expect_dict)

single_stock_prices['C']['prices'][0] =  {date, high, low, open, close, volume, adjclose, formatted_date}

while....
expect_dict = {high, volume, formatted_date, low, adjclose, date, close, open}

**Comment by JECSand** [comment]
Hi Crendon,

Thank you for reporting this issue.
I am looking into this issue now and will post a more detailed report within the next few days.

**Comment by JECSand** [comment]
Hi Crendon,

The issue revolved around timezones. The date string wasn't being transformed into an UTC Unix timestamp, but a local timezone Unix timestamp in the format_date function. This caused different historical price data values to be returned depending on the environments timezone. This has been fixed with the new v1.2 release.

Let me know if you have anymore issues.

Thanks!
