### ISSUE TITLE
An Error occurred when using the Yahoo Financials V0.4

### ISSUE THREAD

**Issue by johannesbambang** [JECSand/yahoofinancials#3]
I receive an error  when I was using Yahoo Financials V0.4. File "C:\ProgramData\Anaconda3\lib\site-packages\yahoofinancials_init_.py", line 93, in format_date split_date = in_date.split('-') AttributeError: 'datetime.date' object has no attribute 'split' 

For further details please see https://stackoverflow.com/questions/51367447/valueerror-timestamp-out-of-range-for-platform-localtime-gmtime-function/51406873#51406873

**Comment by JECSand** [comment]
Hi Johannes,
I just released version 0.6 of the module. In it I addressed your time stamp error (a) and your error from trying to get historical stock price data for ^FTSE (b).

a. For the time-stamp error, I re-factored the format_date method to properly handle unix datetime values older than 1/1/1970. I also added a check to ensure the method returned only a date, not a datetime value. Please let me know if this solves your problem.

b. The reason the module breaks when you try to get historical stock price data for ^FTSE is because that data is not available on Yahoo Finance. ^FTSE (and I am sure there are others) does not have a historical price data table. The only way to get this data is from the interactive chart. I have not had much time to look into this yet. In the interim, I added an exception handler around the _scrap_data method that will handle the error and return a null value for the ticker there is no data for to avoiding breaking your process. It will return as such:

{
  "^FTSE": null
}


Also to see this issue in action yourself, go ahead and navigate to both of these following URLs:

https://finance.yahoo.com/quote/^DJI/history?period1=741416400&period2=1530334800&interval=1d&filter=history&frequency=1d

and

https://finance.yahoo.com/quote/^FTSE/history?period1=741416400&period2=1530334800&interval=1d&filter=history&frequency=1d

The URL below is where that price data will need to come from for tickers like ^FTSE:
https://finance.yahoo.com/chart/^FTSE

Once again please let me know if the v0.6 aren't working for you still. I am going to close this issue for now. However if you have any other problems relating to this, I'll re-open it.
https://pypi.org/project/yahoofinancials/0.6/

Thanks for reporting this bug!
