### ISSUE TITLE
Consider to support currency rate?

### ISSUE THREAD

**Issue by lyc2345** [JECSand/yahoofinancials#8]
Hi, Nice library!
Is currency rates history supported in the future?

**Comment by JECSand** [comment]
Thanks!

**I do want to add currency rate history to the module.** It's something that I have looked into. All of the currency pairs listed at this URL should be available eventually:
https://finance.yahoo.com/currencies

**The only hold up is that we need to find a way to scrap the data from Yahoo Finance's ChartIq interactive charts without a web driver** (spirit of the module is no web driver for easy configuration).
https://finance.yahoo.com/chart/ETHUSD%3DX

**Solving this problem is also critical to getting all of the index stock data.** Indexes such as FTSE's historical stock price data is only available via that chart. **That chart reading functionality is the biggest todo list item left for being at version 1.0.** 

I will try to get to it eventually (hopefully in the next month or two when work slows down for me. Probably 12 - 16 hours of solid work to get this I'd guess). It has seemed pretty tricky. However if someone finds a way to scrap that data and wants to contribute the code to the module. I'd more than welcome that.

**Comment by lyc2345** [comment]
Very glad to hear that!
I will also do some research to scrap data from chart. But I am a newbie lol

**Comment by JECSand** [comment]
That's fine! We all started as newbies. This is how you get better though.

To help you get started if you want to give it a shot:

**1) Fork the current YF v0.7 master branch and go to a Yahoo Finance web-page with a chart to find the hidden data in the web-page:**

    https://finance.yahoo.com/chart/%5EFTSE

    or

    https://finance.yahoo.com/quote/^FTSE/chart?p=^FTSE

     **Hardest part due to unfriendly URL and a hard to find data-store FYI**
     * Ensure the max range is selected (better to just get all of the data in one call vs many).
     * Ensure the correct reporting interval is selected based on the inputted interval.
     * Find and read Data Object containing stock data used by Yahoo Finance ChartIq chart. ('Hardest Part')

**2) Add new dynamic url creation line for chart data pulls on line 259 inside _create_dict_ent()**

**3) Hash out the returned data:**

   * Find def _scrape_data(self, url, tech_type, statement_type) starting on line 117.
   * Add new regex search under line 128 to use for when chart data is needed (as the chart data is NOT located in context store).
   * Add new elif block under line 133 that hashes out and stores the newly added chart's hashed out datastore/datasource.
   * Modify except block under line 258 to rerun _scrape_data() for the Chart stock price data if fails.
   * If stock data is coming from the chart, ensure the data's format matches that of a normal HistoricalPriceStore data return.
   * Ensure stock data from chart flows downstream using HistoricalPriceStore's logic without an errors. Add new handler if err.

**Bonus - Historical Currency Data**
3) Add New report types for currency historical data using variations of the new logic from above once stock prices is working:
 
   * Add currency: ['currency'] under line 74.
   * Set up currency reports to run through similair logic as historical prices.
   * Add a new get_currency_data(self, statement_type='income', tech_type='', report_name='', hist_obj={}) method under line 333.
   * Add a new get_historical_currency_data(self, start_date, end_date, time_interval) method under line 439.

Once you are done we can test everything. If it is good, I'll merge it into the master branch and release the next version!

Let me know if you need any further help. Thanks again and I'll post back here when I had time to pursue this more.

**Comment by lyc2345** [comment]
Very useful tutorial! I can't wait to trying it out this weekend!
Appreciate!

**Comment by JECSand** [comment]
Np!

Also I think I finally found a way to do all of this. I'll start building it out when I get home from work tonight.

**Comment by JECSand** [comment]
Alright,

Version 0.9 of YF is now up on pip, and I have added the ability to pull historical pricing data for currencies, cryptocurrencies, and commodity futures.
Here are lists of all of the currencies, cryptos and futures you can now pull data for:
https://finance.yahoo.com/currencies
https://finance.yahoo.com/cryptocurrencies
https://finance.yahoo.com/commodities

v0.9 has also enhanced the historical stock data as well by adding a few new handy attributes such as the currency the asset price is listed in. This version also addresses the missing data for symbols such as ^FTSE. There should be a lot less symbols not returning data now.

All of the details for the new functionality mentioned in the post can be found on the YahooFinancials ReadMe.

Anyway I am going to go ahead and close this issue now. Feel free to open another if any enhancement ideas/bugs come up.

Thank you for using YahooFinancials!

**Comment by lyc2345** [comment]
I try it out and work perfect!
Thanks a lot!
